Repository Str4nge/HacktoberFest2k22, pull requests merged in 2022-10, with the labels that each got.

#2 Update DecimalToBinary.py
  python/BinaryToDecimal.py
  python/DecimalToBinary.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#7 Create Decimal -> Hex for hacktoberfest-2022
  python/DecimalToHex.py
  python/ReadMe.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#4 added peak-finding algorithm for hacktoberfest
  C_Cpp/Peak_finding.cpp
  C_Cpp/ReadMe.md
Labels: hacktoberfest, hacktoberfest-2022

#5 Create sumofnaturalnos.py
  python/sumofnaturalnos.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#8 Create Rock Paper Scissor game
  python/Rock Paper Scissor game
Labels: hacktoberfest, hacktoberfest-2022

#9 First commit
  python/basicMath.py
Labels: hacktoberfest, hacktoberfest-2022

#10 ancestor matrix from binary tree
  python/ancestor_matrix.py
Labels: hacktoberfest, hacktoberfest-2022

#11 Polynomial Regression
  python/Polynomial_Regression.py
Labels: hacktoberfest, hacktoberfest-2022

#12 xor decrypt
  python/xor-decrypt.py
Labels: hacktoberfest, hacktoberfest-2022

#13 C program to find number of keywords in a given text file!!
  C_Cpp/To_find_keywords.c
  C_Cpp/To_find_keywords.txt
Labels: hacktoberfest, hacktoberfest-2022

#14 Add files via upload
  C_Cpp/reversingno.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#15 Create Check Leap Year Using Nested if.cpp
  C_Cpp/Check Leap Year Using Nested if.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#16 added guessNumber.py
  python/guessNumber.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#17 Add taxation_calculation.py
  python/taxation_calculation.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#18 Added my first program Alphabet.c
  C_Cpp/Alphabet.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#19 Add SnakeGame.py
  python/SnakeGame.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#20 Take A Break Project
  python/TakeABreak.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#21 Create tictactoe.py
  python/tictactoe.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#22 Create Binary Search Tree C++.cpp
  C_Cpp/Binary Search Tree C++.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#23 two sum added
  C_Cpp/two sum.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#25 addition of two number
  python/addition.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#24 Leetcode palindrome soln
  C_Cpp/Leetcode Palindrome fast solution.cpp
  C_Cpp/ReadMe.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#26 Create BinarySearch.cpp
  C_Cpp/BinarySearch.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#27 Create Array.java
  java./Array.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#28 XML To Database using JAVA 8
  Java/XMLParser.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#29 This is used to get the data from a big XML file
  Java/XMLParser1.Java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#30 HeapbyAdityaVerma.cpp
  C_Cpp/HeapbyAdityaVerma.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#35 Integer to Roman
  Java/IntegertoRoman.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#34 Roman to Integer
  Java/Solution.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#36 Create swap.cpp
  C++/swap.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#38 Infix to postfix using stack
  infixtopostfix.c
  linkedlist.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#39 Adding Binary Search Trees (inorder)
  python/binary_search_tree.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#42 Added some Programs on Java
  C++/HelloWorld.c++
  C++/InputOutput.c++
  C++/conditionalStatement.c++
  C++/datatypes.c++
  C++/forloop.c++
  Java/AppleAndOrange.java
  Java/AraaySum.java
  Java/BestTimeBuySell.java
  Java/BigInteger.java
  Java/BinaryTreeInorder.java
  Java/BinaryTreeMaximumDepth.java
  Java/BinaryTreePostorder.java
  Java/BinaryTreePreoder.java
  Java/BinaryTree_PathSum.java
  Java/BuildArrayPermutation.java
  Java/CompareTriplets.java
  Java/ConcatenationOfArray.java
  Java/ContainsDuplicate.java
  Java/ContainsDuplicate2.java
  Java/Datatypes.java
  Java/DecodeXORedArray.java
  Java/DupliacteWords.java
  Java/FibonacciNumber.java
  Java/FinalValueOfVariable.java
  Java/InsertInBST.java
  Java/IntersectionArray.java
  Java/Java1DArray.java
  Java/JavaEndofLine.java
  Java/JavaFormatting.java
  Java/JavaIntToString.java
  Java/JavaLoops.java
  Java/LinearSearch.java
  Java/LoneleyInteger.java
  Java/LowestCommonAncestorBST.java
  Java/MaximumSubarraySum.java
  Java/MergeSortedArray.java
  Java/MissingNumber.java
  Java/NumberLineJumps.java
  Java/NumberOfStepsToReducTillZero.java
  Java/RemoveDuplicatesArray.java
  Java/RemoveElement.java
  Java/RunningSumOfArray.java
  Java/SearchInBST.java
  Java/SearchInsertPosition.java
  Java/SingleNumber.java
  Java/SolveMefirst.java
  Java/SortArrayByParity.class
  Java/SortArrayByParity.java
  Java/Stdin_Stdout.java
  Java/Stdin_StdoutII.java
  Java/SymmetricTree.java
  Java/TwoSum.java
  Java/TwoSumInputIsBST.java
  Java/WelcomeTojava.java
  Java/arraysumlong.java
  Java/ifElse.java
  Java/javaLoopII.java
  Java/plusOne.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#45 Calculator
  Calculator.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#48 Create Longest Palindromic Substring.py
  python/Longest Palindromic Substring.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#55 merageArray
  Java/merageArray.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#49 Create Subset with given Target
  C++/Subset with given Target
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#51 Polynomial subtraction using linked lists.
  polysub.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#53 doubly ended linked list (All functions)
  doubly_ended_linkedlist.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#54 Created dot-animate.py
  python/dot-animate.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#56 Added dir Data Analysis and some analysis on Russia-Ukrain dataset using python.
  python/DataAnalysis/datasets/Russia-UkrainWar/russia_losses_equipment.csv
  python/DataAnalysis/datasets/Russia-UkrainWar/russia_losses_personnel.csv
  python/DataAnalysis/datasets/Russia-UkrainWar/war.ipynb
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#59 issue #58 creating quiz app using python
  python/Quiz_app.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#60 Created CycleDetectionLinkedList.java
  Java/CycleDetectionLinkedList.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#66 M Coloring Problem using recursion in C++
  C++/M Coloring Problem
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#71 Create temperature_converter.py
  python/temperature_converter.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#73 Added reverse a linked list
  Java/reverse_a_linked_list.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#72 Create Factorialoflargenumbers.cpp
  C++/Factorialoflargenumbers.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022
